### ISSUE TITLE
Mismatch on geometrical non linear code coming from you guide

### ISSUE THREAD

**Issue by sunrise125** [ritchie46/anaStruct#77] opened 2021-03-04 06:15 UTC
Hi,
the following code is kept from your
# Collection of examples of 2D structural analysis in Python with anaStruct framework 
# Open Source project by **Ritchie Vink** - https://github.com/ritchie46/anaStruct
but some errors arise.
May I know the reason?
Thanks in advance

# nolin.py
from anastruct import SystemElements
#
ss = SystemElements(EA=15000, EI=5000)
ss.add_element(location=[[0, 0], [0, 5]])
ss.add_element(location=[[0, 5], [5, 5]])
ss.add_element(location=[[5, 5], [5, 0]])
ss.add_support_hinged(node_id=1)
ss.add_support_hinged(node_id=4)
ss.q_load(element_id=2, q=-10)
a = ss.solve(geometrical_non_linear=True, discretize_kwargs=dict(n=20))
print(*a)
ss.show_structure()
#EOF: nolin.py
'''
C:\Training>python nolin.py
Traceback (most recent call last):
  File "nolin.py", line 11, in <module>
    a = ss.solve(geometrical_non_linear=True, discretize_kwargs=dict(n=20))
  File "C:\Users\Alfabeta\AppData\Local\Programs\Python\Python38\lib\site-packages\anastruct\fem\system.py", line 6
49, in solve
    self.buckling_factor = system_components.solver.geometrically_non_linear(
  File "C:\Users\Alfabeta\AppData\Local\Programs\Python\Python38\lib\site-packages\anastruct\fem\system_components\
solver.py", line 140, in geometrically_non_linear
    buckling_system.discretize(**discretize_kwargs)
  File "C:\Users\Alfabeta\AppData\Local\Programs\Python\Python38\lib\site-packages\anastruct\fem\system.py", line 1
505, in discretize
    ss.q_load(
  File "C:\Users\Alfabeta\AppData\Local\Programs\Python\Python38\lib\site-packages\anastruct\fem\system.py", line 9
24, in q_load
    self.plotter.max_q, max(abs(q[i][0]), abs(q[i][1]))
TypeError: bad operand type for abs(): 'list'
'''

**Comment by smith120bh** [comment] 2022-12-31 07:17
@sunrise125 : This may have been fixed with an earlier correction, as I am unable to reproduce this with the current `master` version of anastruct. Please try again, and let me know if you can still reproduce this somehow!

Thank you

**Closed by smith120bh** 2022-12-31 07:17 UTC
